# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' WoodburySpecial
#' Computes the inverse of D + UU^T where
#' D is a diagonal matrix
#' U is a low dimensional matrix
#'
#' @param D is a vector of the diagonal of D
#' @param U is the low rank matrix
#' @export
WoodburySpecial <- function(D, U) {
    .Call(`_PolyMixed_WoodburySpecial`, D, U)
}

#' Update a Cholesky factor R of Q=R'R
#' to R of Q+XX'= R'R
#'
#' @param R upper triangel matrix
#' @param x is a matrix
#'
CholUpdate <- function(R, U) {
    .Call(`_PolyMixed_CholUpdate`, R, U)
}

getTValues <- function(index, Xu, uX, Sigma_U, Y) {
    .Call(`_PolyMixed_getTValues`, index, Xu, uX, Sigma_U, Y)
}

getTValuesDiagS <- function(index, Xu, uX, Sigma_U, Y) {
    .Call(`_PolyMixed_getTValuesDiagS`, index, Xu, uX, Sigma_U, Y)
}

#' @export
crossSelect <- function(X1, X2, cross) {
    invisible(.Call(`_PolyMixed_crossSelect`, X1, X2, cross))
}

#' @export
mixing_population <- function(X1, X2, Z1, Z2, n_gen, lambda_cross) {
    invisible(.Call(`_PolyMixed_mixing_population`, X1, X2, Z1, Z2, n_gen, lambda_cross))
}

